services:
  db: 
    image: mysql
    container_name: dbsql
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=laravel
    restart: always
    ports:
      - "3306:3306"
  
  app:
    build: .
    container_name: app
    volumes:
      - ./api:/app/laravel
    depends_on:
      - db
    ports:
      - "8000:8000"
      - "5173:5173"